### ISSUE TITLE
numpy import error On Ubuntu Linux version 24.04

### ISSUE THREAD

**Issue by wwashing** [barjac/freedv-rade-build#1]
File "/usr/lib/python3/dist-packages/matplotlib/transforms.py", line 49, in <module>
    from matplotlib._path import (
ImportError: numpy.core.multiarray failed to import
Error: importing radae_txe

**Comment by barjac** [comment]
Please run the script again carefully following every step of the instructions.
Several Ubuntu-24.04 installs have been done recently without issue.
If there is still a problem run the script again with:
`$ freedv-rade-build/freedv-rade-build | tee freedv-rade-build.log`
Attach the freed-rade-build.log here. Thanks.
